apiVersion: v1
kind: Service
metadata:
  name: densityservice
  labels:
    app: triplogic
    servicename: densityservice
spec:
  ports:
    - port: 9221
      name: grpc
  selector:
    app: densityservice
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: densityservice
  labels:
    app: densityservice
    tier: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authservice
        tier: backend
        phase: beta
        version: v1
    spec:
      containers:
      - name: authservice
        image: asia.gcr.io/tugas-akhir-hana/density-vehicle:v1
        ports:
        - name: grpc-auth
          containerPort: 9221

      restartPolicy: Always
